### ISSUE TITLE
With shadow dom enabled, tailwind adds shadow styles

### ISSUE THREAD

**Issue by Poimen** [Poimen/stencil-tailwind-plugin#1]
Stencil imports use a `?...shadow` that causes tailwind jit to input shadow styles into the final out even when shadows are not used

**Comment by pranav-js** [comment]
can you please fix this? I was planning to use this plugin for my stencil web components project. tailwind 3.0.0 has lot to offer with JIT enabled.

**Comment by Poimen** [comment]
As memory serves it adds a single class for tailwind v3. This equates to a couple of bytes per component. Is this a showstopper?

I'll have a look at it in the new year. Not sure the time to do it, as well as the added runtime parsing is worth it, though...

**Comment by pranav-js** [comment]
didn't get what you meant by `As memory serves it adds a single class for tailwind v3.` can you please elaborate

**Comment by Poimen** [comment]
As in, the tailwind class that is added is:
```css
.shadow{--tw-shadow:0 1px 3px 0 rgba(0,0,0,.1),0 1px 2px -1px rgba(0,0,0,.1);--tw-shadow-colored:0 1px 3px 0 var(--tw-shadow-color),0 1px 2px -1px var(--tw-shadow-color);box-shadow:var(--tw-ring-offset-shadow,0 0 #0000),var(--tw-ring-shadow,0 0 #0000),var(--tw-shadow)}
```

So those bytes are what are included - so 270 bytes extra...
