### ISSUE TITLE
Missing classes with Stencil Hydrate

### ISSUE THREAD

**Issue by mayerraphael** [Poimen/stencil-tailwind-plugin#29]
As this plugin is a rollup plugin (no pluginType: 'css'), this is run AFTER the stencil hydrate plugin is run.

The problem:

Stencil hydrate adds comments to the css classes so the scoped classes can later be rewritten to work hydrated component again.

Now with this plugin, all tailwind inline-classes and utility classes, which generate more classes (`:hover`, `lg:, md:` and so on) are added AFTER the comments for the hydrate package have been created. Resulting in broken styles with SSR.

We have created our own plugin thanks to your source code (and searching the tailwindcss source) which runs as a `css` plugin, fully creating all css classes BEFORE any Stencil plugin runs.

One drawback is that we need to load the tsx file manually (like tailwindcss does with changedContent) and don't have any _sourceTsx already set (has same content as sourceCss), as the plugin is run only on css files.

Thanks for all your hard work.

**Comment by Poimen** [comment]
oooooo, hydrate - I thought I had fixed that 🙈  🤦‍♂️ 

Do you know if this happens on the example repo, or have a example to play with?

Also, the code drop here ... is this your plugin or an example of a/the fix?

**Comment by mayerraphael** [comment]
I removed the code from the original post, you can find our adjusted plugin here: https://gist.github.com/mayerraphael/bb3122ece5900671b5cb85dbe46a1e8e

I will check your example repo later.

**Comment by Poimen** [comment]
Interesting ... the HMR plugin add dependencies and writes the css to stencil buffers. I'm guessing the secondary buffer write is probably what does it seeing that the HMR only deals with the CSS files and updates stencils css files.

Should probably make that more explicit if that is the cause - like an actual plugin/implementation that maps better to hydrate.

**Comment by mayerraphael** [comment]
Yes the problem is that only the css transform plugins run before Stencils Hydrate worker plugin.

This also means that every component MUST have a stylesheet, as other components are not processed. 

You can check this behavior in your example.

1. Add `dist-hydrate-script` to your output targets in the  `stencil.config.ts`

```js
outputTargets: [
    {
      type: 'dist',
      esmLoaderPath: '../loader',
    },
    {
      type: 'dist-hydrate-script',
    },
    ...
}
```

2. Remove `tailwindHMR()` from `plugins`
3. run `npm run build`
4. Check the generated `hydrate/index.js` 

The last css classes of FooterNav (footerNavCss)

```css
.duration-300{transition-duration:.3s}.ease-in-out{transition-timing-function:cubic-bezier(.4,0,.2,1)}
```
With `tailwindHMR()`

```css
/*!@.duration-300*/.duration-300.sc-footer-nav{transition-duration:.3s}/*!@.ease-in-out*/.ease-in-out.sc-footer-nav{transition-timing-function:cubic-bezier(.4,0,.2,1)}@media (min-width:1024px){.lg\\:flex-row{flex-direction:row}.lg\\:gap-4{gap:1rem}.lg\\:rounded-md{border-radius:.375rem}}
```

You can see that 

1. The classes without tailwindHMR did not get scoped (sc-footer-nav suffix missing)
2. Classes which are generated by tailwind are missing (`lg:`, `hover:`,  , etc)
3. The scoped-comments are missing, so Stencil hydration cannot convert those classes back again.
